#+LaTeX_CLASS: beamer
#+LaTeX_HEADER: \mode<presentation>
#+LaTeX_HEADER: \usetheme{CambridgeUS}
#+LaTeX_HEADER: \usecolortheme{seagull}
#+LaTeX_HEADER: \setbeameroption{hide notes}
#+LaTeX_HEADER: \institute{FOSSMeet/2013}
#+TITLE: Git Unchained
#+AUTHOR: Ramkumar Ramachandra
#+DATE: 23rd February 2013

#+BEGIN_LaTeX
\def\newblock{\hskip .11em plus .33em minus .07em} % Hack to make BibTeX work with LaTeX
\newcommand{\hl}[1 ]{\colorbox{lightgray}{#1}} % New command: hl to highlight text
#+END_LaTeX

* Part I: Introducing the object store
** What does the object store look like?
#+BEGIN_LaTeX
\begin{center}\includegraphics[scale=0.45]{res/object-model.pdf}\end{center}
#+END_LaTeX
\note[itemize]{
\item You haven't seen this image before; pay close attention.
\item Every object is identified by compulsory SHA1 after zlib
      compression: this is the key!
\item Commits are in a DAG: multiple parents.
\item Now for the main difference: deltas are not necessarily against
      the previous revision! When packing, the full object store data
      is available :)
\item For good packing heuristics, we decide based on many parameters
      like type, filename, and filesize. Using a good window size,
      generate deltas against n "close" objects and write the smallest
      delta. This has been engineered by Linus and Peter for maximum
      efficiency: for example, in xdelta, delta removing data is
      cheaper than adding data.
\item When writing packfiles, there's an index with an ordering based
      on "recency" or reachability from HEAD. The "loose" objects can
      be found using the packfile index.
}
** What is inside a tree?
#+BEGIN_LaTeX
\begin{center}
\begin{alltt}
$ git ls-tree HEAD^\{tree\}
\scriptsize
100644 blob 5e98806c6cc246acef5f539ae191710a0c06ad3f    .gitattributes
100644 blob 6669bf0c6c9a0b42f74e2ed189350a6a9f11f17d    .gitignore
100644 blob c7e86183001a00ad2105765708b5b59852ef6640    .mailmap
100644 blob 536e55524db72bd2acf175208aef4f3dfc148d42    COPYING
040000 tree 53e11809b8bdfcd6486ba8aa2afd8839c4c73cfe    Documentation
100755 blob e9f7abca91b96c2f9c99744c49adefe04a4daf56    GIT-VERSION-GEN
120000 blob bdce3136ea5164d82f0d25d0a7a8b50181f572f7    RelNotes
100644 blob 59b394eea38494d5dfa525e28ca949e5a03efcf5    blob.h
040000 tree 5fb111c6a71bf720621724f54bec4679041f8ab6    block-sha1
100644 blob 2bef1e7e71b7cb3375b3d96fab5c4f20e0c3adff    branch.c
040000 tree 41d60c10d7a21e786ec863bfc5f75a073dc7b8e5    builtin
[...]
\end{alltt}
\end{center}
#+END_LaTeX
\note[itemize]{
\item <mode> SP <type> SP <object> TAB <file>
}
* Part II: Advanced Git commands
** Swiss Army knives
#+BEGIN_LaTeX
\begin{center}\includegraphics[scale=1.5]{res/swiss-army-knife.jpg}\end{center}
#+END_LaTeX
** blame
#+BEGIN_LaTeX
\begin{center}
\begin{alltt}
$ git blame sequencer.c
\scriptsize
26ae337b (Ramkumar Ramachandra  2011-08-04 16:09:11 +0530    1) #include "cache.h"
26ae337b (Ramkumar Ramachandra  2011-08-04 16:09:11 +0530    2) #include "sequencer.h"
26ae337b (Ramkumar Ramachandra  2011-08-04 16:09:11 +0530    3) #include "dir.h"
043a4492 (Ramkumar Ramachandra  2012-01-11 23:45:57 +0530    4) #include "object.h"
043a4492 (Ramkumar Ramachandra  2012-01-11 23:45:57 +0530    5) #include "commit.h"
043a4492 (Ramkumar Ramachandra  2012-01-11 23:45:57 +0530    6) #include "tag.h"
043a4492 (Ramkumar Ramachandra  2012-01-11 23:45:57 +0530    7) #include "run-command.h"
043a4492 (Ramkumar Ramachandra  2012-01-11 23:45:57 +0530    8) #include "exec_cmd.h"
043a4492 (Ramkumar Ramachandra  2012-01-11 23:45:57 +0530    9) #include "utf8.h"
043a4492 (Ramkumar Ramachandra  2012-01-11 23:45:57 +0530   10) #include "cache-tree.h"
043a4492 (Ramkumar Ramachandra  2012-01-11 23:45:57 +0530   11) #include "diff.h"
043a4492 (Ramkumar Ramachandra  2012-01-11 23:45:57 +0530   12) #include "revision.h"
043a4492 (Ramkumar Ramachandra  2012-01-11 23:45:57 +0530   13) #include "rerere.h"
043a4492 (Ramkumar Ramachandra  2012-01-11 23:45:57 +0530   14) #include "merge-recursive.h"
043a4492 (Ramkumar Ramachandra  2012-01-11 23:45:57 +0530   15) #include "refs.h"
b27cfb0d (Neil Horman           2012-04-20 10:36:15 -0400   16) #include "argv-array.h"
043a4492 (Ramkumar Ramachandra  2012-01-11 23:45:57 +0530   17) 
043a4492 (Ramkumar Ramachandra  2012-01-11 23:45:57 +0530   18) #define GIT_REFLOG_ACTION "GIT_REFLOG_ACTION"
26ae337b (Ramkumar Ramachandra  2011-08-04 16:09:11 +0530   19) 
5ed75e2a (Miklos Vajna          2012-09-14 08:52:03 +0200   20) const char sign_off_header[] = "Signed-off-by: ";
[...]
\end{alltt}
\end{center}
#+END_LaTeX
** pickaxe
#+BEGIN_LaTeX
\begin{center}
\begin{verbatim}
$ git log --oneline -S 'static char *get_encoding(const char *message)'
043a449 sequencer: factor code out of revert builtin
d685654 revert: clarify label on conflict hunks
81b50f3 Move 'builtin-*' into a 'builtin/' subdirectory
52fae7d Missing statics.
\end{verbatim}
\end{center}
#+END_LaTeX
** filter-branch
#+BEGIN_LaTeX
\begin{center}
\begin{columns}
\begin{column}[c]{5cm}
\begin{center}\includegraphics[scale=0.45]{res/filter-funnel.png}\end{center}
\end{column}
\begin{column}[c]{5cm}
\begin{itemize}
\begin{alltt}
\item[] --env-filter
\item[] --tree-filter
\item[] --index-filter
\item[] --parent-filter
\item[] --msg-filter
\item[] --commit-filter
\item[] --tag-name-filter
\item[] --subdirectory-filter
\end{alltt}
\end{itemize}
\end{column}
\end{columns}
\vfill
\begin{verbatim}
$ git filter-branch --tree-filter 'mv blog/_posts . || ;' HEAD
\end{verbatim}
\end{center}
#+END_LaTeX
** read-tree
#+BEGIN_LaTeX
\begin{center}
\begin{alltt}
$ git remote add -f Bproject /path/to/B
$ git merge -s ours --no-commit Bproject/master
$ git read-tree --prefix=dir-B/ -u Bproject/master
$ git commit -m "Merge B project as our subdirectory"
\vfill
See also: Documentation/howto/using-merge-subtree.txt
\end{alltt}
\end{center}
#+END_LaTeX
** rev-parse
#+BEGIN_LaTeX
\begin{center}
\begin{center}\includegraphics[scale=0.5]{res/scene-curtain.png}\end{center}
\vfill
\begin{verbatim}
$ git rev-parse --short origin/master~13^2
073678b
\end{verbatim}
\end{center}
#+END_LaTeX
** rev-list
#+BEGIN_LaTeX
\begin{center}
\begin{verbatim}
$ git rev-list --abbrev-comit --topo-order -5 master~724
261ec7d
59f9b8a
8c5b1ae
f9bc573
c73f384
\end{verbatim}
\end{center}
#+END_LaTeX
* Part III: A small fast-import detour
** What does the protocol look like?
#+BEGIN_LaTeX
\begin{columns}
\begin{column}[c]{2cm}
\includegraphics[scale=0.2]{res/protocol.pdf}
\end{column}
\begin{column}[c]{8cm}
\scriptsize
\begin{alltt}
\underline{commit} refs/heads/remote-helper
\underline{mark} :30
\underline{author} Ramkumar Ramachandra <artagnon@gmail.com> 1170314617 +0530
\underline{committer} Junio C Hamano <gitster@pobox.com> 1170325891 +0100
\underline{data} 111
vcs-svn: Fix delete operation in the treap

\underline{from} :28
\underline{M} 100644 :29 vcs-svn/trp.h

\underline{blob}
\underline{mark} :31
\underline{data} 4941
/*
 * C macro implementation of treaps.
[...]
\end{alltt}
\end{column}
\end{columns}
#+END_LaTeX
\note[itemize]{
\item fast-import uses the object API directly: it's built only for
      speed: almost 3x as fast as svnrdump.
\item Commands: commit, author, mark, data, from, blob
\item Before the CP, only fast-import can access the objects it wrote;
      this makes sense in the context of efficient packing discussed
      earlier.
\item Use it programmatically: remote helper.
}
** The concept of a remote helper
#+BEGIN_LaTeX
\begin{center}\includegraphics[scale=0.3]{res/remote-helper.pdf}\end{center}
#+END_LaTeX
\note[itemize]{
\item Confession: My GSoC project was to build a remote helper for
      Subversion. We managed to write the infrastructure.
\item Remote helper is simply a program with a set of commands like a
      shell; capabilities are fetch, import, push etc.
\item Gitcore sets up UNIX pipes to call the remote helper: it
      consumes/ produces a fast-import stream
\item When Git core doesn't know how to handle the protocol,
      transport-helper.c looks for a remote helper to connect to. The
      rest is the remote helper's problem.
}
* Part IV: Conclusion
** What you should hack on when you go home
#+BEGIN_LaTeX
\begin{columns}
\begin{column}[c]{3cm}
\includegraphics[scale=0.2]{res/spanner-hammer.pdf}
\end{column}
\begin{column}[c]{7cm}
\includegraphics[scale=0.3]{res/quadrant.pdf}
\end{column}
\end{columns}
#+END_LaTeX
\note[itemize]{
\item libgit2/ Rugged
}
** Can I have these slides?
#+BEGIN_LaTeX
\begin{alltt}
Ramkumar Ramachandra
artagnon@gmail.com
\url{http://artagnon.com}
Sources: \url{http://github.com/artagnon/authored}
\end{alltt}
\vfill\hfill\includegraphics[scale=0.2]{res/cc.pdf}
#+END_LaTeX
