#+LaTeX_CLASS: beamer
#+LaTeX_HEADER: \mode<presentation>
#+LaTeX_HEADER: \usetheme{CambridgeUS}
#+LaTeX_HEADER: \usecolortheme{beaver}
#+LaTeX_HEADER: \setbeameroption{show notes}
#+LaTeX_HEADER: \institute{FOSS.IN/2010}
#+TITLE: Leveraging the Git object store
#+AUTHOR: Ramkumar Ramachandra
#+DATE: 15 December 2010

#+BEGIN_LaTeX
\def\newblock{\hskip .11em plus .33em minus .07em} % Hack to make BibTeX work with LaTeX
\newcommand{\hl}[1 ]{\colorbox{lightgray}{#1}} % New command: hl to highlight text
#+END_LaTeX

* Part I: The background noise
** Why is everyone obsessed with Git?
#+BEGIN_LaTeX
\begin{center}\includegraphics[scale=0.5]{res/opening.pdf}\end{center}
#+END_LaTeX
\note[itemize]{
\item Filesystems, issue trackers, wikis, databases, and backup systems
\item Why Git? Why not hg, bzr, darcs or SVN?
\item Reason: Simplicity. The Git object model.
\item The applications should indicate what Git really is.
}
** The guts of Git
#+BEGIN_LaTeX
\begin{center}\includegraphics[scale=0.4]{res/logical-layers.pdf}\end{center}
#+END_LaTeX
\note[itemize]{
\item We're going to go all the way down to the object store
\item Everything else is infrastructure
\item The higher layers add limitations and functionality.
\item What's special about the object store?
}
** ... and the guts of the object store
#+BEGIN_LaTeX
\begin{center}\includegraphics[scale=0.7]{res/object-model.png}\end{center}
#+END_LaTeX
\note[itemize]{
\item This image is taken from ProGit, the book.
\item Git is a key-value store: commit, tree, blob and tag.
\item Commits are in a DAG.
}
* Part II: A fast-import crash course
** What does the protocol look like?
#+BEGIN_LaTeX
\begin{columns}
\begin{column}[c]{2cm}
\includegraphics[scale=0.2]{res/protocol.pdf}
\end{column}
\begin{column}[c]{8cm}
\scriptsize
\begin{verbatim}
commit refs/heads/remote-helper 
mark :30
author Ramkumar Ramachandra <artagnon@gmail.com> 1170314617 +0530
committer Junio C Hamano <gitster@pobox.com> 1170325891 +0100
data 111
vcs-svn: Fix delete operation in the treap

from :28
M 100644 :29 vcs-svn/trp.h

blob
mark :31
data 4941
/*
 * C macro implementation of treaps.
 *
 * Usage:
[...]
\end{verbatim}
\end{column}
\end{columns}
#+END_LaTeX
\note[itemize]{
\item fast-import uses the object API directly.
\item Commands: commit, author, mark, data, from, blob
\item ~350 commits/sec
}
** The concept of a remote helper
#+BEGIN_LaTeX
\begin{center}\includegraphics[scale=0.3]{res/remote-helper.pdf}\end{center}
#+END_LaTeX
\note[itemize]{
\item Confession: My GSoC project was to build a remote helper for Subversion
\item Before the CP, only fast-import can access the objects it wrote
}
** Bi-directional how?
#+BEGIN_LaTeX
\begin{columns}
\begin{column}[c]{7cm}
\begin{itemize}
\item Keep track of written blobs using marks
\item Fetch a previously written blob
\item Apply the delta
\item Write back the new blob
\end{itemize}
\end{column}
\begin{column}[c]{3cm}
\includegraphics[scale=0.2]{res/bidi.pdf}
\end{column}
\end{columns}
#+END_LaTeX
\note[itemize]{
\item 'cat-blob' to retrive previously written blobs
\item 'ls-tree' to to start from a non-zero point
\item fast-import features -- backward compatibility
}
** The import/export and conversion machinery
#+BEGIN_LaTeX
\begin{columns}
\begin{column}[c]{4cm}
\includegraphics[scale=0.3]{res/gear.pdf}
\end{column}
\begin{column}[c]{6cm}
\begin{itemize}
\end{itemize}
\end{column}
\end{columns}
#+END_LaTeX
\note[itemize]{
}
* Part III: Conclusion
** What you should hack on when you go home
#+BEGIN_LaTeX
\begin{columns}
\begin{column}[c]{3cm}
\includegraphics[scale=0.2]{res/spanner-hammer.pdf}
\end{column}
\begin{column}[c]{7cm}
\begin{itemize}
\item Foreign VCS interop: remote helpers, machinery, revision mapping
\item Gitcore: transport layer, fast-import
\item Related projects: bup, gimd
\item Gitcore re-implementation: libgit2
\item Heavy history rewrite tools: filter-branch
\item Packfile optimization: narrow and sparse clones
\item Heavy-duty validation/ testing tools
\end{itemize}
\end{column}
\end{columns}
#+END_LaTeX
\note[itemize]{
\item SVN interop: svnrdump
\item ESR wrote reposurgeon
\item Sverre wrote hg-remote-hg
\item Vincent wrote libgit2 in SoC 2010
\item The story of replace refs
}
** Can I have these slides?
#+BEGIN_LaTeX
Ramkumar Ramachandra\\
artagnon@gmail.com\\
\url{http://artagnon.com}\\
Source: \url{http://github.com/artagnon/foss.in}\\
\vfill\hfill\includegraphics[scale=0.2]{res/cc.pdf}
#+END_LaTeX
