#+LaTeX_CLASS: beamer
#+LaTeX_HEADER: \mode<presentation>
#+LaTeX_HEADER: \usetheme{CambridgeUS}
#+LaTeX_HEADER: \usecolortheme{seagull}
#+LaTeX_HEADER: \setbeameroption{hide notes}
#+LaTeX_HEADER: \institute{FOSS.IN/2010}
#+TITLE: Leveraging the Git object store
#+AUTHOR: Ramkumar Ramachandra
#+DATE: 15 December 2010

#+BEGIN_LaTeX
\def\newblock{\hskip .11em plus .33em minus .07em} % Hack to make BibTeX work with LaTeX
\newcommand{\hl}[1 ]{\colorbox{lightgray}{#1}} % New command: hl to highlight text
#+END_LaTeX

* Part I: The background noise
** Why is everyone obsessed with Git?
#+BEGIN_LaTeX
\begin{center}\includegraphics[scale=0.5]{res/opening.pdf}\end{center}
#+END_LaTeX
\note[itemize]{
\item Filesystems, issue trackers, wikis, databases, and backup systems
\item Why Git? Why not hg, bzr, darcs or SVN?
\item Reason: Simplicity. The Git object model.
\item The applications should indicate what Git really is.
}
** The guts of Git
#+BEGIN_LaTeX
\begin{center}\includegraphics[scale=0.4]{res/logical-layers.pdf}\end{center}
#+END_LaTeX
\note[itemize]{
\item This is a plumbing-only picture: missing in-core object caching,
      tree traversal, pretty printing, commit list, index
\item Everything else is infrastructure
\item The higher layers add limitations and functionality.
\item What's special about the object store?
}
** ... and the guts of the object store
#+BEGIN_LaTeX
\begin{center}\includegraphics[scale=0.45]{res/object-model.pdf}\end{center}
#+END_LaTeX
\note[itemize]{
\item You haven't seen this image before; pay close attention.
\item Git is a key-value store: commit, tree, blob and tag.
\item Commits are in a DAG.
}
* Part II: A fast-import crash course
** What does the protocol look like?
#+BEGIN_LaTeX
\begin{columns}
\begin{column}[c]{2cm}
\includegraphics[scale=0.2]{res/protocol.pdf}
\end{column}
\begin{column}[c]{8cm}
\scriptsize
\begin{alltt}
\underline{commit} refs/heads/remote-helper 
mark :30
\underline{author} Ramkumar Ramachandra <artagnon@gmail.com> 1170314617 +0530
\underline{committer} Junio C Hamano <gitster@pobox.com> 1170325891 +0100
\underline{data} 111
vcs-svn: Fix delete operation in the treap

\underline{from} :28
\underline{M} 100644 :29 vcs-svn/trp.h

\underline{blob}
\underline{mark} :31
\underline{data} 4941
/*
 * C macro implementation of treaps.
 *
 * Usage:
[...]
\end{alltt}
\end{column}
\end{columns}
#+END_LaTeX
\note[itemize]{
\item fast-import uses the object API directly.
\item Commands: commit, author, mark, data, from, blob
\item ~350 commits/sec
}
** The concept of a remote helper
#+BEGIN_LaTeX
\begin{center}\includegraphics[scale=0.3]{res/remote-helper.pdf}\end{center}
#+END_LaTeX
\note[itemize]{
\item Confession: My GSoC project was to build a remote helper for Subversion
\item Before the CP, only fast-import can access the objects it wrote
}
** Bi-directional how?
#+BEGIN_LaTeX
\begin{columns}
\begin{column}[c]{7cm}
\begin{enumerate}
\item[1 ] Keep track of written blobs using marks
\item[2 ] Fetch a previously written blob
\item[3 ] Apply the delta
\item[4 ] Write back the new blob
\end{enumerate}
\end{column}
\begin{column}[c]{3cm}
\includegraphics[scale=0.2]{res/bidi.pdf}
\end{column}
\end{columns}
#+END_LaTeX
\note[itemize]{
\item 'cat-blob' to retrive previously written blobs
\item 'ls-tree' to to start from a non-zero point
\item fast-import features -- backward compatibility
}
** The import/ export machinery
#+BEGIN_LaTeX
\begin{columns}
\begin{column}[c]{6cm}
\includegraphics[scale=0.3]{res/svn-layout.pdf}
\end{column}
\begin{column}[c]{4cm}
\scriptsize
\begin{alltt}
Node-path: commons/STATUS
Node-kind: (file|dir)
Node-action: (change|add|delete|replace)
\end{alltt}
\vfill
\begin{alltt}
svn:special
svn:author
svn:date
svn:executable
\end{alltt}
\end{column}
\end{columns}
#+END_LaTeX
\note[itemize]{
\item Fundamentally different object models
\item The story of replace refs
}
* Part III: Conclusion
** What you should hack on when you go home
#+BEGIN_LaTeX
\begin{columns}
\begin{column}[c]{3cm}
\includegraphics[scale=0.2]{res/spanner-hammer.pdf}
\end{column}
\begin{column}[c]{7cm}
\includegraphics[scale=0.3]{res/quadrant.pdf}
\end{column}
\end{columns}
#+END_LaTeX
\note[itemize]{
\item Gitcore + fi: transport layer, fast-import, (Heavy history
      rewrite tools) filter-branch
\item fi: Heavy-duty validation/ testing tools
\item Gitcore: work on fast-import part of libgit2
\item Git-related things: bup, gimd
\item fi + machinery: remote helpers, revision mapping, reposurgeon
\item Machinery: svnrdump
}
** Can I have these slides?
#+BEGIN_LaTeX
Ramkumar Ramachandra\\
artagnon@gmail.com\\
\url{http://artagnon.com}\\
Source: \url{http://github.com/artagnon/foss.in}\\
\vfill\hfill\includegraphics[scale=0.2]{res/cc.pdf}
#+END_LaTeX
