#+LaTeX_CLASS: beamer
#+LaTeX_HEADER: \mode<presentation>
#+LaTeX_HEADER: \usetheme{CambridgeUS}
#+LaTeX_HEADER: \usecolortheme{beaver}
#+LaTeX_HEADER: \setbeameroption{show notes}
#+LaTeX_HEADER: \institute{FOSS.IN/2010}
#+TITLE: Leveraging the Git object store
#+AUTHOR: Ramkumar Ramachandra
#+DATE: 15 December 2010

#+BEGIN_LaTeX
\def\newblock{\hskip .11em plus .33em minus .07em} % Hack to make BibTeX work with LaTeX
\newcommand{\hl}[1 ]{\colorbox{lightgray}{#1}} % New command: hl to highlight text
#+END_LaTeX

* Introduction
** Why is everyone obsessed with Git?
#+BEGIN_LaTeX
\begin{columns}
\begin{column}[c]{4cm}
\includegraphics[scale=0.3]{res/logo.png}
\end{column}
\begin{column}[c]{6cm}
\begin{itemize}
\item bup
\item gimd
\item gollum
\item hg-git, git-bzr etc.
\end{itemize}
\end{column}
\end{columns}
#+END_LaTeX
\note[itemize]{
\item Why build stuff on Git - what's the big deal?
\item Git is stupid. Read: extensible.
}
** What's inside Git?
#+BEGIN_LaTeX
\begin{center}\includegraphics[scale=0.4]{res/logical-layers.png}\end{center}
#+END_LaTeX
\note[itemize]{
\item We're going to go all the way down to the object store
\item Everything else is infrastructure
\item Everything goes through the object API (except fast-import)
\item What's special about the object store?
}
** ... and deeper into the object store we go
#+BEGIN_LaTeX
\begin{center}\includegraphics[scale=0.7]{res/object-model.png}\end{center}
#+END_LaTeX
\note[itemize]{
\item We're going to go all the way down to the object store
\item Everything else is infrastructure
\item Everything goes through the object API (except fast-import)
\item What's special about the object store?
}
* The fast-import protocol
** There's a protocol?
#+BEGIN_LaTeX
\begin{columns}
\begin{column}[c]{2cm}
\includegraphics[scale=0.2]{res/protocol.png}
\end{column}
\begin{column}[c]{8cm}
\scriptsize
\begin{verbatim}
commit refs/heads/remote-helper 
mark :30
author Ramkumar Ramachandra <artagnon@gmail.com> 1170314617 +0530
committer Junio C Hamano <gitster@gmail.com> 1170325891 +0100
data 111
vcs-svn: Fix the delete operation in the treap

Signed-off-by: Ramkumar Ramachandra <artagnon@gmail.com>
from :28
M 100644 :29 vcs-svn/trp.h

blob
mark :31
data 4941
/*
 * C macro implementation of treaps.
 *
 * Usage:
[...]
\end{verbatim}
\end{column}
\end{columns}
#+END_LaTeX
\note[itemize]{
\item Disclaimer: Simplified for easy of understanding
\item fast-import bypasses everything
\item Before the CP, only fast-import can access the objects it wrote
\item ~350 commits/sec
}
** The world of remote helpers
#+BEGIN_LaTeX
\begin{columns}
\begin{column}[c]{2cm}
\includegraphics[scale=0.2]{res/logo.png}
\end{column}
\begin{column}[c]{8cm}
\begin{itemize}
\item Remote helpers!
\end{itemize}
\end{column}
\end{columns}
#+END_LaTeX
\note[itemize]{
\item Confession: My GSoC project was to build a remote helper for Subversion
\item fast-import bypasses everything
\item Before the CP, only fast-import can access the objects it wrote
\item ~350 commits/sec
}
** Wait, what about other version control systems?
#+BEGIN_LaTeX
\begin{columns}
\begin{column}[c]{2cm}
\includegraphics[scale=0.2]{res/logo.png}
\end{column}
\begin{column}[c]{8cm}
\begin{itemize}
\item subversion/svnrdump
\end{itemize}
\end{column}
\end{columns}
#+END_LaTeX
\note[itemize]{
\item Confession: My GSoC project was to build a remote helper for Subversion
\item Before the CP, only fast-import can access the objects it wrote
\item ~120 revisions/sec
}
* The Meat
** Yes, I'm going to talk about ongoing work
#+BEGIN_LaTeX
\begin{columns}
\begin{column}[c]{2cm}
\includegraphics[scale=0.2]{res/logo.png}
\end{column}
\begin{column}[c]{8cm}
\begin{itemize}
\item cat-blob and ls-tree
\item Persistence
\item map
\item What happens when upstream rewrites history?
\item fast-import $\to$ dumpfilev3 conversion
\item The remote helper
\end{itemize}
\end{column}
\end{columns}
#+END_LaTeX
\note[itemize]{
\item To apply deltas and start from a non-zero point
\item Mapping SVN revisions to Git revisions seamlessly
\item The story of replace refs
\item Reject non-ff pushes
}
* Conclusion
** How this talk was useful to you, and what you should hack on when you go home
#+BEGIN_LaTeX
\begin{columns}
\begin{column}[c]{2cm}
\includegraphics[scale=0.2]{res/logo.png}
\end{column}
\begin{column}[c]{8cm}
\begin{itemize}
\item cat-blob and ls-tree
\item Persistence
\item map
\item What happens when upstream rewrites history?
\item fast-import $\to$ dumpfilev3 conversion
\item The remote helper
\end{itemize}
\end{column}
\end{columns}
#+END_LaTeX
\note[itemize]{
\item To apply deltas and start from a non-zero point
\item Mapping SVN revisions to Git revisions seamlessly
\item The story of replace refs
\item Reject non-ff pushes
}
** Appendix
#+BEGIN_LaTeX
\nocite{*}
\bibliographystyle{acm}
\bibliography{haskell-internals}
#+END_LaTeX
** Who am I again?
#+BEGIN_LaTeX
Ramkumar Ramachandra\\
artagnon@gmail.com\\
\url{http://artagnon.com}\\
Indian Institute of Technology, Kharagpur\\
Presentation source available on \url{http://github.com/artagnon/foss.in}
#+END_LaTeX
